url:
  fileUrl: D:/file/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.98.93.238:3306/vhr?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s
server:
  port: 8082

mybatis:
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: org.sang.model
  mapper-locations: classpath:mapper/*.xml
