url:
  fileUrl: D:/file
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.98.93.238:3306/vhr?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 1000
      min-idle: 500
    timeout: 1000
  servlet:
    multipart:
      max-file-size: "1000MB"
      max-request-size: "10000MB"
server:
  port: 8082

mybatis:
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: org.sang.model
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/table/*.xml

mail:
  user: 1104935833@qq.com
  password: gyflrrsfvpylgggd